services:
  - type: web
    name: scraper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://your-frontend-url.onrender.com
      - key: PYTHON_VERSION
        value: 3.9.0 